name: iut_ecms
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ui based
  flutter_svg: ^2.0.16
  lottie: ^3.1.3

  # network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # state management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # dart core
  get_it: ^8.0.2
  injectable: ^2.5.0
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_gen_runner: ^5.8.0
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  jwt_decoder: ^2.0.1
  file_picker: ^8.1.4
  logger: ^2.5.0
  elegant_notification: ^2.4.0
  focus_detector: ^2.0.1
  keyboard_dismisser: ^3.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  easy_localization_generator: ^0.3.3

dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/localization/
    - assets/svgs/

flutter_gen:
  output: lib/core/gen
  integrations:
    flutter_svg: true
    lottie: true